[package]
name = "magic_craft_bevy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.18"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
